<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
<?php 
echo $this->headTitle();echo "\n"; 
echo $this->headMeta();echo "\n";
echo $this->headStyle();echo "\n";
echo $this->headLink();echo "\n"; 

echo $this->headScript();echo "\n";
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action 	= Zend_Controller_Front::getInstance()->getRequest()->getActionName();

?>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="navbar navbar-inverse " role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Супер магазин</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            
            <?php if($this->indentity == false){?>
            <li <?php if ($controller == 'index' && $action == 'index') {echo 'class="active"';}?>><a href="/">Главная</a></li>
            <li <?php if ($controller == 'user' && $action == 'reg') {echo 'class="active"';}?>><a href="/user/reg/">Регистрация</a></li>
            <li <?php if ($controller == 'user' && $action == 'login') {echo 'class="active"';}?>><a href="/user/login/">Логин</a></li>
            <?php }else {?>
            <li <?php if ($controller == 'index' && $action == 'index') {echo 'class="active"';}?>><a href="/">Добро пожаловать <b><?php echo $this->indentity->name?></b></a></li>
            <li <?php if ($controller == 'shop' && $action != 'add') {echo 'class="active"';}?>><a href="/shop/">Список товаров</a></li>
           	<li <?php if ($controller == 'shop' && $action == 'add') {echo 'class="active"';}?>><a href="/shop/add">Добавить товар</a></li> 
           
            <li><a href="/user/logout">Выход</a></li>
            <?php }?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
	<div class="content">
<?php echo $this->layout()->content; ?>
</div>
</div>
</body>
</html>