<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<HTML xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
<head>

	<meta charset="utf-8">

	<?php 
$static = 'http://smotrisport.tv';
$static = '';
$this->headLink()->headLink(array('rel'=>'shortcut icon','href'=>$static.'/favicon.ico','type'=>'image/x-icon'),'PREPEND');
$this->headLink()->appendStylesheet($static.'/css/style.css')
;

$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')


;
$this->headScript()->appendFile ('https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js')
	->appendFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js')
	->appendFile($static.'/js/socket.io.js')
	->appendFile($static.'/js/custom.js')
	->appendFile($static.'/js/app.js')

	

	;
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action 	= Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
   <?php echo $this->headTitle();echo "\n"; ?>
	<?php echo $this->headMeta();echo "\n"; ?>
	<?php echo $this->headScript();echo "\n"; ?>
	<?php echo $this->headStyle();echo "\n"; ?>
	<?php echo $this->headLink();echo "\n"; ?>
	<script type="text/javascript" src="//vk.com/js/api/openapi.js?105"></script>
	<script type="text/javascript">
	  VK.init({apiId: 4048123, onlyWidgets: true});
	</script>
</head>

<body ng-app="myApp">
<a id="toTop" href="#top">↑</a>
	<div class="wrapper">
		
		<div class="center">
			<DIV class="pro5"></DIV>

			<DIV class="logo">
				<A href="/">
					<IMG src="/img/logo.png" title="RockyHockey.net: прямые трансляции хоккея">
					<?php if ($controller == 'index' && $action == 'index'){?>
					<h1>RockyHockey.net: прямые трансляции хоккея</h1>
					<?php }else {?>
					<span>RockyHockey.net: прямые трансляции хоккея</span>
					<?php }?>
				</A>
			</DIV>
			
			<DIV class="search">			
				<div class="ya-site-form ya-site-form_inited_no" onclick="return {'bg': '#f2f2f2', 'publicname': '\u041c\u044b \u0437\u0430 \u0441\u043f\u043e\u0440\u0442.\u0440\u0443', 'target': '_self', 'language': 'ru', 'suggest': true, 'tld': 'ru', 'site_suggest': true, 'action': '/search', 'webopt': false, 'fontsize': 14, 'arrow': false, 'fg': '#000000', 'searchid': '2101113', 'logo': 'rb', 'websearch': false, 'type': 3}">
					<form action="http://yandex.ru/sitesearch" method="get" target="_blank">
						<input type="hidden" name="searchid" value="2101113" />
						<input type="hidden" name="l10n" value="ru" />
						<input type="hidden" name="reqenc" value="" />
						<input type="text" name="text" value="" />
						<input type="submit" value="Найти" />
					</form>
				</div>
				<style type="text/css">.ya-page_js_yes .ya-site-form_inited_no { display: none; }</style>
				<script type="text/javascript">(function(w,d,c){var s=d.createElement('script'),h=d.getElementsByTagName('script')[0],e=d.documentElement;(' '+e.className+' ').indexOf(' ya-page_js_yes ')===-1&&(e.className+=' ya-page_js_yes');s.type='text/javascript';s.async=true;s.charset='utf-8';s.src=(d.location.protocol==='https:'?'https:':'http:')+'//site.yandex.net/v2.0/js/all.js';h.parentNode.insertBefore(s,h);(w[c]||(w[c]=[])).push(function(){Ya.Site.Form.init()})})(window,document,'yandex_site_callbacks');</script>
			</DIV>

			<DIV class="social">
				<script type="text/javascript">(function() {
				  if (window.pluso)if (typeof window.pluso.start == "function") return;
				  if (window.ifpluso==undefined) { window.ifpluso = 1;
					var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
					s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
					s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
					var h=d[g]('body')[0];
					h.appendChild(s);
				  }})();</script>
				<div data-user="2083848018" class="pluso" data-background="transparent" data-options="medium,round,line,horizontal,nocounter,theme=04" data-services="vkontakte,facebook,twitter,odnoklassniki,google,moimir,email"></div>			
			</div>		
			<DIV class="pro15"></DIV>
			
			<DIV class="menu_sm">
				<A href="/turnirs/khokkyey-chyempionat-nhl/" class="menu_sm_a"><img src="/upload/video/7c/4a/video_52a09e262f2ac.jpg">NHL<SPAN class="new-span">hot</SPAN></A>
				<A href="/turnirs/khokkyey-chyempionat-vkhl/" class="menu_sm_a"><img src="/upload/video/eb/bb/video_52a09e279e01d.jpg">ВХЛ<SPAN class="new-span">hot</SPAN></A>
				<A href="/turnirs/khokkyey-chyempionat-kkhl/" class="menu_sm_a"><img src="/upload/video/aa/7a/video_52a09e26392db.jpg">КХЛ<SPAN class="new-span">hot</SPAN></A>
				<A href="/turnirs/chyempionat-mira-po-khokkyeyu/" class="menu_sm_a"><img src="/upload/video/cb/9b/video_52a09e266a3fc.jpg">Чемпионат Мира</A>
				<A href="/turnirs/chyempionat-shvyeytsarii-po-khokkyeyu-liga-a/" class="menu_sm_a"><img src="/upload/video/ab/7c/video_52a09e273e4d9.jpg">Чемпионат Швейцарии. Лига A</A>
				<A href="/turnirs/chyempionat-shvyetsii-po-khokkyeyu/" class="menu_sm_a"><img src="/upload/video/bc/8b/video_52a09e277f3ed.jpg">Чемпионат Швеции</A>
			</DIV>
			
			<DIV class="pro5"></DIV>
			
			<DIV class="menu2">
				<A class="menu2_n active" href="/">Главная</A>
				<A class="menu2_n" href="/match/">Трансляции хоккея</A>
				<A class="menu2_n" href="/video/">Обзоры матчей</A>
				<A class="menu2_n" href="/news/">Новости</A>
			</DIV>
			
			<DIV class="pro20"></DIV>
			
			
<?php echo $this->layout()->content; ?>
	<DIV class="bottom_line">
				<DIV class="bottom_counters">
					<!-- Yandex.Metrika informer -->
					<a href="http://metrika.yandex.ru/stat/?id=23294071&amp;from=informer"
					target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/23294071/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
					style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:23294071,lang:'ru'});return false}catch(e){}"/></a>
					<!-- /Yandex.Metrika informer -->

					<!-- Yandex.Metrika counter -->
					<script type="text/javascript">
					(function (d, w, c) {
						(w[c] = w[c] || []).push(function() {
							try {
								w.yaCounter23294071 = new Ya.Metrika({id:23294071,
										webvisor:true,
										clickmap:true,
										trackLinks:true,
										accurateTrackBounce:true});
							} catch(e) { }
						});

						var n = d.getElementsByTagName("script")[0],
							s = d.createElement("script"),
							f = function () { n.parentNode.insertBefore(s, n); };
						s.type = "text/javascript";
						s.async = true;
						s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

						if (w.opera == "[object Opera]") {
							d.addEventListener("DOMContentLoaded", f, false);
						} else { f(); }
					})(document, window, "yandex_metrika_callbacks");
					</script>
					<noscript><div><img src="//mc.yandex.ru/watch/23294071" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
					<!-- /Yandex.Metrika counter --> 
					  
					<!--LiveInternet counter--><script type="text/javascript"><!--
					document.write("<a href='http://www.liveinternet.ru/click' "+
					"target=_blank><img src='//counter.yadro.ru/hit?t12.6;r"+
					escape(document.referrer)+((typeof(screen)=="undefined")?"":
					";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
					screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
					";"+Math.random()+
					"' alt='' title='LiveInternet: показано число просмотров за 24"+
					" часа, посетителей за 24 часа и за сегодня' "+
					"border='0' width='88' height='31'><\/a>")
					//--></script><!--/LiveInternet-->
					
					<!-- Rating@Mail.ru counter -->
					<script type="text/javascript">//<![CDATA[
					var _tmr = _tmr || [];
					_tmr.push({id: "2435118", type: "pageView", start: (new Date()).getTime()});
					(function (d, w) {
					   var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
					   ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
					   var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
					   if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
					})(document, window);
					//]]></script><noscript><div style="position:absolute;left:-10000px;">
					<img src="//top-fwz1.mail.ru/counter?id=2435118;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
					</div></noscript>
					<!-- //Rating@Mail.ru counter -->

					<!-- Rating@Mail.ru logo -->
					<a href="http://top.mail.ru/jump?from=2435118">
					<img src="//top-fwz1.mail.ru/counter?id=2435118;t=479;l=1" 
					style="border:0;" height="31" width="88" alt="Рейтинг@Mail.ru" /></a>
					<!-- //Rating@Mail.ru logo -->
					
					<!-- hit.ua -->
					<a href='http://hit.ua/?x=91676' target='_blank'>
					<script language="javascript" type="text/javascript"><!--
					Cd=document;Cr="&"+Math.random();Cp="&s=1";
					Cd.cookie="b=b";if(Cd.cookie)Cp+="&c=1";
					Cp+="&t="+(new Date()).getTimezoneOffset();
					if(self!=top)Cp+="&f=1";
					//--></script>
					<script language="javascript1.1" type="text/javascript"><!--
					if(navigator.javaEnabled())Cp+="&j=1";
					//--></script>
					<script language="javascript1.2" type="text/javascript"><!--
					if(typeof(screen)!='undefined')Cp+="&w="+screen.width+"&h="+
					screen.height+"&d="+(screen.colorDepth?screen.colorDepth:screen.pixelDepth);
					//--></script>
					<script language="javascript" type="text/javascript"><!--
					Cd.write("<img src='http://c.hit.ua/hit?i=91676&g=0&x=1"+Cp+Cr+
					"&r="+escape(Cd.referrer)+"&u="+escape(window.location.href)+
					"' border='0' width='88' height='31' "+
					"alt='hit.ua: сейчас на сайте, посетителей и просмотров за сегодня' title='hit.ua: сейчас на сайте, посетителей и просмотров за сегодня'/>");
					//--></script></a>
					<!-- / hit.ua -->
					
					<script>
					  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
					  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
					  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
					  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

					  ga('create', 'UA-46257375-1', 'rockyhockey.net');
					  ga('send', 'pageview');

					</script>
				</DIV>
				
				<DIV class="bottom_copy">© 2013 RockyHockey.net: прямые трансляции хоккея<BR>
					Любое использование материалов приветствуется при гиперссылке
				</DIV>
				
				<a class="site-map" href="/sitemap.xml" title="Карта сайта">Карта сайта</a>
			</DIV>


		</div>   
	</div>
</body>
</html>